name: geostatistics-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal>=3.9.2
  - geopandas
  - folium
  - pysal
  - libpysal
  - esda
  - seaborn
  - numpy
  - matplotlib
  - jupyter