name: geostatistics-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal=3.9.2
  - geopandas=1.0.1
  - folium=0.19.4
  - libpysal=4.12.1
  - esda=2.6.0
  - seaborn=0.13.2
  - numpy=2.0.2
  - matplotlib=3.10.0
  - jupyter